"use strict";
/**
 * genz codegen (Node.js port) - mirrors the three compiler-py/genz/codegen_*.py modules.
 */

const PROPERTY_ALIASES = {
  bg: "background", color: "color", size: "font-size", weight: "font-weight",
  font: "font-family", pad: "padding", margin: "margin", round: "border-radius",
  gap: "gap", width: "width", height: "height", shadow: "box-shadow",
  border: "border", opacity: "opacity", cursor: "cursor", transition: "transition",
  display: "display", align: "align-items", justify: "justify-content",
  position: "position", top: "top", left: "left", right: "right", bottom: "bottom",
  z: "z-index", line: "line-height", spacing: "letter-spacing", overflow: "overflow",
};

const NO_VALUE_PROPS = {
  center: "text-align: center;", flex: "display: flex;", grid: "display: grid;",
  hidden: "display: none;", bold: "font-weight: bold;", italic: "font-style: italic;",
  underline: "text-decoration: underline;", pointer: "cursor: pointer;",
  rounded: "border-radius: 9999px;",
};

function declToCss(prop, value) {
  value = value.trim();
  if (!value && NO_VALUE_PROPS[prop]) return NO_VALUE_PROPS[prop];
  const cssProp = PROPERTY_ALIASES[prop] || prop;
  return `${cssProp}: ${value};`;
}

function generateCss(styleRules) {
  const out = [];
  for (const rule of styleRules) {
    out.push(`${rule.selector} {`);
    for (const decl of rule.decls) out.push(`  ${declToCss(decl.prop, decl.value)}`);
    out.push("}", "");
  }
  return out.join("\n").replace(/\n+$/, "") + "\n";
}

const VOID_TAGS = new Set(["img", "input", "br", "hr", "meta", "link"]);
const EVENT_ATTR = {
  click: "onclick", hover: "onmouseover", submit: "onsubmit", change: "onchange",
  input: "oninput", load: "onload", dblclick: "ondblclick", keyup: "onkeyup",
  keydown: "onkeydown", mouseover: "onmouseover", mouseout: "onmouseout",
  focus: "onfocus", blur: "onblur",
};

function escText(s) { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
function escAttr(s) { return escText(s).replace(/"/g, "&quot;"); }

function renderElement(el, indent = 0) {
  const pad = "  ".repeat(indent);
  const attrs = [];
  if (el.elemId) attrs.push(`id="${escAttr(el.elemId)}"`);
  if (el.classes.length) attrs.push(`class="${escAttr(el.classes.join(" "))}"`);
  for (const [name, value] of Object.entries(el.attrs)) attrs.push(`${name}="${escAttr(value)}"`);
  for (const [verb, js] of Object.entries(el.events)) {
    attrs.push(`${EVENT_ATTR[verb] || "on" + verb}="${escAttr(js)}"`);
  }
  const attrStr = attrs.length ? " " + attrs.join(" ") : "";

  if (VOID_TAGS.has(el.tag)) return `${pad}<${el.tag}${attrStr}>`;

  if (el.children.length) {
    const inner = el.children.map((c) => renderElement(c, indent + 1)).join("\n");
    const textLine = el.text ? `${pad}  ${escText(el.text)}\n` : "";
    return `${pad}<${el.tag}${attrStr}>\n${textLine}${inner}\n${pad}</${el.tag}>`;
  }
  const text = el.text ? escText(el.text) : "";
  return `${pad}<${el.tag}${attrStr}>${text}</${el.tag}>`;
}

function generateBody(body) {
  return body.map((el) => renderElement(el, 1)).join("\n");
}

function generateHtml(title, body, cssHref, jsHref) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escText(title)}</title>
  <link rel="stylesheet" href="${cssHref}">
</head>
<body>
${generateBody(body)}
  <script src="${jsHref}"></script>
</body>
</html>
`;
}

function generateJs(vars, rawScriptLines) {
  const lines = ["// generated by the CodeGenZ compiler - edits here will be overwritten", ""];
  for (const v of vars) lines.push(`let ${v.name} = ${v.expr};`);
  if (vars.length) lines.push("");
  if (rawScriptLines.length) { lines.push(...rawScriptLines); lines.push(""); }
  return lines.join("\n");
}

module.exports = { generateCss, generateHtml, generateBody, generateJs };
