"""
genz.codegen_js
-----------------
Produces the companion .js file: top-level `var` statements become
`let` declarations, and any `script:` block is emitted close to
verbatim (CodeGenZ does not try to "simplify" raw JS - that block is
your escape hatch to the real language underneath).
"""

from typing import List
from .ast_nodes import VarDecl


def generate_js(vars_: List[VarDecl], raw_script_lines: List[str]) -> str:
    lines = ["// generated by the CodeGenZ compiler - edits here will be overwritten", ""]
    for v in vars_:
        lines.append(f"let {v.name} = {v.expr};")
    if vars_:
        lines.append("")
    if raw_script_lines:
        lines.extend(raw_script_lines)
        lines.append("")
    return "\n".join(lines)
