"""
genz.codegen_js
-----------------
Produces the companion .js file: top-level `var` statements become
`let` declarations, and any `script:` block is emitted close to
verbatim (CodeGenZ does not try to "simplify" raw JS - that block is
your escape hatch to the real language underneath).
"""

from typing import List
from .ast_nodes import (
    VarDecl, WhenBlock, ActSet, ActAdjust, ActVisibility, ActClass, ActCall, ActIf,
)


def _esc_js_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _action_lines(action, depth: int) -> List[str]:
    pad = "  " * depth
    if isinstance(action, ActSet):
        if action.target.startswith("text:"):
            eid = action.target[len("text:"):]
            return [f'{pad}document.getElementById("{eid}").textContent = {action.expr};']
        if action.target.startswith("value:"):
            eid = action.target[len("value:"):]
            return [f'{pad}document.getElementById("{eid}").value = {action.expr};']
        return [f"{pad}{action.target} = {action.expr};"]

    if isinstance(action, ActAdjust):
        op = "+" if action.op == "increase" else "-"
        return [f"{pad}{action.name} = {action.name} {op} ({action.expr});"]

    if isinstance(action, ActVisibility):
        value = "" if action.show else "none"
        return [f'{pad}document.getElementById("{action.target_id}").style.display = "{value}";']

    if isinstance(action, ActClass):
        return [f'{pad}document.getElementById("{action.target_id}").classList.{action.op}("{_esc_js_string(action.cls)}");']

    if isinstance(action, ActCall):
        fn = "alert" if action.kind == "alert" else "console.log"
        return [f"{pad}{fn}({action.expr});"]

    if isinstance(action, ActIf):
        lines = [f"{pad}if ({action.cond}) {{"]
        for a in action.then:
            lines.extend(_action_lines(a, depth + 1))
        lines.append(f"{pad}}}")
        if action.else_:
            lines[-1] = f"{pad}}} else {{"
            for a in action.else_:
                lines.extend(_action_lines(a, depth + 1))
            lines.append(f"{pad}}}")
        return lines

    raise TypeError(f"unknown action node: {action!r}")


def generate_when_js(when_blocks: List[WhenBlock]) -> List[str]:
    if not when_blocks:
        return []
    lines = ['document.addEventListener("DOMContentLoaded", function () {']
    for wb in when_blocks:
        lines.append(f'  document.querySelector("{wb.selector}").addEventListener("{wb.event}", function (event) {{')
        for action in wb.actions:
            lines.extend(_action_lines(action, 2))
        lines.append("  });")
    lines.append("});")
    return lines


def generate_js(vars_: List[VarDecl], raw_script_lines: List[str], when_blocks: List[WhenBlock] = None) -> str:
    when_blocks = when_blocks or []
    lines = ["// generated by the CodeGenZ compiler - edits here will be overwritten", ""]
    for v in vars_:
        lines.append(f"let {v.name} = {v.expr};")
    if vars_:
        lines.append("")
    if raw_script_lines:
        lines.extend(raw_script_lines)
        lines.append("")
    when_lines = generate_when_js(when_blocks)
    if when_lines:
        lines.extend(when_lines)
        lines.append("")
    return "\n".join(lines)
